/********************************************************************
*
* GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE INTERRUPT MAP. header file
*
* Copyright (C) 2015-2023 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_INTERRUPT_MAP_H_
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_INTERRUPT_MAP_H_

#include <drivers/hw_include/cslr.h>
#include <drivers/hw_include/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE
*/

#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_0_CBASS0_DEFAULT_ERR_INTR_0           (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_1_CBASS_INFRA1_DEFAULT_ERR_INTR_0     (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_10_CBASS_RT_DATA0_DEFAULT_ERR_INTR_0  (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_11_WKUP_CBASS_SAFE1_DEFAULT_ERR_INTR_0 (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_12_CBASS_AUDIO0_DEFAULT_ERR_INTR_0    (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_2_AEN_MAIN_DBG_CBASS0_DEFAULT_ERR_INTR_0 (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_3_MCU_CBASS0_DEFAULT_ERR_INTR_0       (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_4_CBASS_CENTRAL2_DEFAULT_ERR_INTR_0   (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_5_CBASS_IPCSS0_DEFAULT_ERR_INTR_0     (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_6_CBASS_MCASP0_DEFAULT_ERR_INTR_0     (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_7_CBASS_MISC_PERI0_DEFAULT_ERR_INTR_0 (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_8_WKUP_CBASS0_DEFAULT_ERR_INTR_0      (0U)
#define CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_MAIN_ERR_INTR_9_CBASS_RT_CFG0_DEFAULT_ERR_INTR_0    (0U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_GLUELOGIC_SOC_CBASS_ERR_INTR_GLUE_INTERRUPT_MAP_H_ */

