/********************************************************************
*
* WKUP_DEEPSLEEP_SOURCES0 INTERRUPT MAP. header file
*
* Copyright (C) 2015-2023 Texas Instruments Incorporated.
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*    Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
*    Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in the
*    documentation and/or other materials provided with the
*    distribution.
*
*    Neither the name of Texas Instruments Incorporated nor the names of
*    its contributors may be used to endorse or promote products derived
*    from this software without specific prior written permission.
*
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
*  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
*  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
*  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
*  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
*  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
*  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
*  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
*  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
#ifndef CSLR_WKUP_DEEPSLEEP_SOURCES0_INTERRUPT_MAP_H_
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_INTERRUPT_MAP_H_

#include <drivers/hw_include/cslr.h>
#include <drivers/hw_include/tistdtypes.h>
#ifdef __cplusplus
extern "C"
{
#endif

/*
* List of intr sources for receiver: WKUP_DEEPSLEEP_SOURCES0
*/

#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_WKUP_I2C0_CLKSTOP_WAKEUP_0 (0U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_WKUP_UART0_CLKSTOP_WAKEUP_0 (1U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_MCU_GPIO0_GPIO_LVL_0       (2U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_WKUP_ICEMELTER0_PSC_FORCE_POWER_ON_0 (3U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_WKUP_TIMER0_TIMER_CLKSTOP_WAKEUP_0 (5U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_WKUP_TIMER1_TIMER_CLKSTOP_WAKEUP_0 (6U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_WKUP_RTCSS0_RTC_EVENT_PEND_0 (7U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_GLUELOGIC_INVERTED_MAIN_RESETZ_LATCHED_INTR_0 (8U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_USB0_USB_WAKEUP_CLKSTOP_WAKEUP_0 (9U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_GLUELOGIC_IO_SWAKEUP_MAIN_IO_0 (16U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_GLUELOGIC_IO_SWAKEUP_MCU_IO_0 (17U)
#define CSLR_WKUP_DEEPSLEEP_SOURCES0_ISAM62_DM_WAKEUP_DEEPSLEEP_SOURCES_GLUELOGIC_IO_SWAKEUP_CAN_USART_IO_0 (18U)

#ifdef __cplusplus
}
#endif
#endif /* CSLR_WKUP_DEEPSLEEP_SOURCES0_INTERRUPT_MAP_H_ */

